name: Node Project CI
on: 
  push:
    brances: [ main ]
  pull_request: [ main ]
jobs: 
  build: 
    strategy:
      matrix: 
        node-version: [14.x, 16.x, 18.x]
    runs-on: ubuntu-latest
    steps: 
      -uses: actions/checkout@v2
      -uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix.node-version}}
      -run: npm install
      -run: npm run build --prefix client